export const SLOT_BOOKING_REQUEST = "USER_DETAILS_REQUEST";
export const SLOT_BOOKING_SUCCESS = "SLOT_BOOKING_SUCCESS";
export const SLOT_BOOKING_FAIL = "SLOT_BOOKING_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";